language: python
services:
  - postgresql
  - docker
cache:
  - pip
  - yarn
install:
  - pip install -r wangwang/requirements.txt
  - pip install -r wangwang/dev-requirements.txt
  - pip freeze

jobs:
  include:
    - stage: test
      name: "Code style"
      python: 3.6
      script:
        - cd wangwang && make check
    - stage: test
      name: "Unit test"
      python: 3.6
      script:
        - psql -c 'create database test;' -U postgres
        - cd wangwang
        - make makemigrations
        - make migrate
        - make test
      env:
        - ENV=test
    - stage: build
      name: "Build backend"
      python: 3.6
      script:
        - cd wangwang
        - COMMIT_ID=$(git rev-parse --short HEAD)
        - docker build -t wangwang .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker images
        - docker tag wangwang $DOCKER_USERNAME/wangwang:$COMMIT_ID
        - docker push $DOCKER_USERNAME/wangwang:$COMMIT_ID
        - echo "Build Success!"
      env:
        - DOCKER_USERNAME=zhaoqi99
    - stage: build
      name: "Build frontend"
      script:
        - echo "Build Success!"
      env:
        - DOCKER_USERNAME=zhaoqi99
    - stage: deploy
      name: "Deploy backend"
      script:
        - echo "Deploy Success!"
    - stage: deploy
      name: "Deploy frontend"
      script:
        - echo "Deploy Success!"
stages:
  - build
  - deloy
  # - name: build
  #   if: branch = master 
  # - name: deploy
  #   if: branch = master    
  # - test
        