language: python
python:
  - "3.5"
  - "3.6"
services:
  - mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS dev;'
install:
  - pip install flake8
  - pip install -r requirements.txt
  - pip freeze
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - cd wangwang
script:
  - flake8 .
  - isort *.py -c -vb
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test