language: python
python:
  - "3.5"
  - "3.6"
services:
  - postgresql
cache:
  - pip
env:
  - ENV=test
install:
  - pip install -r wangwang/requirements.txt
  - pip install -r wangwang/dev-requirements.txt
  - pip freeze
before_script:
  - psql -c 'create database test;' -U postgres
  - cd wangwang
script:
  - make check
  - make makemigrations
  - make migrate
  - make test