language: python
python:
  - "3.5"
  - "3.6"
services:
  - postgresql
cache:
  - pip
env:
  - ENV=test
install:
  - pip install -r wangwang/requirements.txt
  - pip install -r wangwang/dev-requirements.txt
  - pip freeze
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd wangwang
script:
  - flake8 .
  - isort *.py -c -vb
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test