language: python
python:
  - "3.5"
  - "3.6"
services:
  - mysql
cache:
  - pip
install:
  - pip install flake8
  - pip install -r requirements.txt
  - pip freeze
before_script:
  - mysql -e 'SET GLOBAL character_set_server=utf8;'
  - mysql -e 'SET GLOBAL character_set_database=utf8; '
  - mysql -e 'DROP DATABASE IF  EXISTS dev;'
  - mysql -e 'CREATE DATABASE dev;'
  - cd wangwang
script:
  - flake8 .
  - isort *.py -c -vb
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test