# Generated by Django 2.2.7 on 2020-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='participant',
            field=models.CharField(blank=True, default='', help_text='可以为空(无处理人的情况，如结束状态)、username、多个username(以,隔开)、部门id、角色id、脚本,机器人等', max_length=100, verbose_name='参与者'),
        ),
    ]
