# Generated by Django 2.2.7 on 2019-11-24 18:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('expired', models.DateTimeField(default=datetime.datetime(2019, 11, 24, 18, 10, 37, 709232, tzinfo=utc), verbose_name='token expire time')),
                ('token', models.TextField(blank=True, verbose_name='token')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='account.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ('user',),
            },
        ),
    ]
