# Generated by Django 2.2.7 on 2019-12-08 09:11

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expired',
            field=models.DateTimeField(default=account.models._default_expire_time, verbose_name='token expire time'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('users', models.ManyToManyField(related_name='user_roles', to='account.User', verbose_name='users')),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'verbose_name': 'Role',
            },
        ),
    ]
