# Generated by Django 2.2.7 on 2020-02-10 15:13

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191208_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.utils.user_avatar_path, verbose_name='avater'),
        ),
    ]
