# Generated by Django 2.2.7 on 2020-02-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200210_2313'),
        ('account', '0004_auto_20200211_1115'),
    ]

    operations = [
    ]
