# Generated by Django 2.2.7 on 2020-02-13 10:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_auto_20200211_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFlowLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('suggestion', models.CharField(blank=True, default='', max_length=1000, verbose_name='处理意见')),
                ('participant_type', models.IntegerField(choices=[(0, '无处理人'), (1, '个人'), (2, '多人'), (3, '部门'), (4, '角色'), (5, '脚本'), (6, '参与人')], default=0, help_text='constant_service中定义', verbose_name='处理人类型')),
                ('participant', models.CharField(blank=True, default='', max_length=50, verbose_name='处理人')),
                ('ticket_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='可以用于记录当前表单数据，json格式', verbose_name='工单数据')),
            ],
            options={
                'verbose_name': '工单流转日志',
                'verbose_name_plural': '工单流转日志',
            },
        ),
        migrations.CreateModel(
            name='TicketRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(blank=True, default='', help_text='工单的标题', max_length=500, verbose_name='标题')),
                ('sn', models.CharField(default=ticket.models.default_sn, help_text='工单的流水号', max_length=25, verbose_name='流水号')),
                ('participant_type', models.IntegerField(choices=[(0, '无处理人'), (1, '个人'), (2, '多人'), (3, '部门'), (4, '角色'), (5, '脚本'), (6, '参与人')], default=0, help_text='0.无处理人,1.个人,2.多人,3.部门,4.角色', verbose_name='当前处理人类型')),
                ('participant', models.CharField(blank=True, default='', help_text='可以为空(无处理人的情况，如结束状态)、username、多个username(以,隔开)、部门id、角色id、脚本文件名等', max_length=100, verbose_name='当前处理人')),
                ('ticket_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='可以用于记录当前表单数据，json格式', verbose_name='工单数据')),
                ('is_end', models.BooleanField(default=False, help_text='工单是否已处于结束状态', verbose_name='已结束')),
                ('creator', models.ForeignKey(help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User')),
                ('parent_ticket', models.ForeignKey(blank=True, help_text='TicketRecord关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_parent_tickets', to='ticket.TicketRecord', verbose_name='父工单')),
            ],
            options={
                'verbose_name': '工单记录',
                'verbose_name_plural': '工单记录',
            },
        ),
    ]
