# Generated by Django 2.2.7 on 2020-02-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrecord',
            name='parent_ticket_state',
            field=models.ForeignKey(blank=True, help_text='与workflow.State关联,子工单是关联到父工单的某个状态下的', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.State', verbose_name='对应父工单状态'),
        ),
        migrations.AddField(
            model_name='ticketrecord',
            name='state',
            field=models.ForeignKey(help_text='与workflow.State关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_tickets', to='workflow.State', verbose_name='当前状态'),
        ),
        migrations.AddField(
            model_name='ticketrecord',
            name='workflow',
            field=models.ForeignKey(help_text='关联的流程', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='ticketflowlog',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.State', verbose_name='当前状态'),
        ),
        migrations.AddField(
            model_name='ticketflowlog',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketRecord'),
        ),
        migrations.AddField(
            model_name='ticketflowlog',
            name='transition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Transition', verbose_name='流转'),
        ),
    ]
